services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: payment_service
      PAYMENT_DEFAULT_PROVIDER: stripe
      STRIPE_ENABLED: "true"
      STRIPE_SECRET_KEY: ""
      STRIPE_WEBHOOK_SECRET: ""
      PAYMOB_ENABLED: "false"
      PAYMOB_API_KEY: ""
      PAYMOB_INTEGRATION_ID: ""
      PAYMOB_IFRAME_ID: ""
      PAYMOB_HMAC_SECRET: ""
    ports:
      - "3000:3000"

volumes:
  pgdata:
